"use client";

import React, { useState, useEffect, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  CloudRain,
  Car,
  Clock,
  MapPin,
  Download,
  RefreshCw,
  AlertCircle,
  ChevronRight,
  Terminal
} from 'lucide-react';

// Ensure these paths are exact to your project structure
import { useTripStore } from '../store/useTripStore';
import { TravelExperienceCoordinator } from '../engine/TravelExperienceCoordinator';
import { handleTravelForm } from './actions/travel';
import { jsPDF } from 'jspdf';
import { ItinerarySkeleton } from '../components/Itinerary/Skeleton';

export default function OmniTraveDashboard() {
  const {
    itinerary,
    setItinerary,
    isRainMode,
    toggleRain,
    isHeavyTraffic,
    toggleTraffic,
    reasoningLog,
    isUpdating,
    setUpdating,
    addLog
  } = useTripStore();

  const [loading, setLoading] = useState(false);
  const [destination, setDestination] = useState('');

  const generateInitialTrip = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setLoading(true);
    const formData = new FormData(e.currentTarget);

    try {
      addLog("Initializing RAG research for 2026 travel data...");
      const result = await handleTravelForm(formData);

      const activities = result.activities.map((a: any, i: number) => ({
        id: `act-${Date.now()}-${i}`,
        time: a.time,
        title: a.title || a.description.split(' - ')[0],
        description: a.description,
        location: destination,
        isIndoor: a.isIndoor || i % 2 === 0,
        coordinates: a.coordinates || { lat: 0, lng: 0 },
        rating: 4.5 + (Math.random() * 0.5),
        topReview: "Absolutely amazing experience! The local culture and atmosphere here are unmatched. Highly recommend visiting early to avoid the crowds.",
        googleMapsUrl: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(a.title || a.description.split(' - ')[0])}`
      }));

      setItinerary(activities);
      addLog(`Engine successfully synchronized for ${destination}.`);
    } catch (err) {
      addLog("Critical Error: RAG synchronization failed.");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleSimulatedPivot = async (type: 'RAIN' | 'TRAFFIC') => {
    setUpdating(true);
    if (type === 'RAIN') toggleRain();
    if (type === 'TRAFFIC') toggleTraffic();

    // Call the engine static method to recalculate
    await TravelExperienceCoordinator.evaluateAndPivot(type, {
      currentItinerary: itinerary
    });

    setUpdating(false);
  };

  const exportToPDF = () => {
    const doc = new jsPDF();
    doc.setFillColor(5, 5, 5);
    doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text(`OMNITRAVE: ${destination.toUpperCase()}`, 20, 30);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Gemini 3 Flash Experience Engine - 2026", 20, 40);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    itinerary.forEach((act, i) => {
      const y = 60 + (i * 20);
      doc.text(`${act.time} | ${act.title}`, 20, y);
      doc.setFontSize(9);
      doc.setTextColor(180, 180, 180);
      doc.text(act.description.substring(0, 80) + "...", 20, y + 7);
      doc.setFontSize(12);
      doc.setTextColor(255, 255, 255);
    });
    doc.save(`OmniTrave_${destination || 'Trip'}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[#050505] text-zinc-100 font-sans selection:bg-indigo-500/30">
      <header className="border-b border-zinc-800/50 bg-black/40 backdrop-blur-xl sticky top-0 z-50">
        <nav className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between" aria-label="Main Navigation">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center shadow-lg shadow-indigo-500/20" aria-hidden="true">
              <MapPin className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold tracking-tight">OMNITRAVE</span>
          </div>
          <button
            onClick={exportToPDF}
            aria-label="Export itinerary as PDF"
            className="flex items-center gap-2 px-4 py-2 bg-zinc-800 hover:bg-zinc-700 rounded-full text-sm transition border border-zinc-700 focus-visible:ring-2 focus-visible:ring-indigo-500 outline-none"
          >
            <Download className="w-4 h-4" /> Export Itinerary
          </button>
        </nav>
      </header>

      <main className="max-w-7xl mx-auto px-6 py-10 grid grid-cols-1 lg:grid-cols-12 gap-8">
        <aside className="lg:col-span-4 space-y-6">
          <section className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-6 shadow-inner" aria-labelledby="config-title">
            <h2 id="config-title" className="text-xs font-bold text-zinc-500 uppercase tracking-[0.2em] mb-4">Trip Configuration</h2>
            <form onSubmit={generateInitialTrip} className="space-y-4">
              <div className="space-y-2">
                <label htmlFor="destination" className="text-[10px] text-zinc-500 ml-1 uppercase">Destination</label>
                <input
                  id="destination"
                  name="destination"
                  placeholder="e.g. Hyderabad, India"
                  className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 focus:border-indigo-500 outline-none transition text-sm"
                  value={destination}
                  onChange={e => setDestination(e.target.value)}
                  required
                  aria-required="true"
                />
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div className="space-y-2">
                  <label htmlFor="budget" className="text-[10px] text-zinc-500 ml-1 uppercase">Budget</label>
                  <input id="budget" name="budget" placeholder="₹40,000" className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 outline-none text-sm focus-visible:border-indigo-500" required />
                </div>
                <div className="space-y-2">
                  <label htmlFor="pace" className="text-[10px] text-zinc-500 ml-1 uppercase">Pace</label>
                  <select id="pace" name="pace" className="w-full bg-zinc-950 border border-zinc-800 rounded-xl p-3 outline-none text-sm appearance-none focus-visible:border-indigo-500">
                    <option>Relaxed</option>
                    <option>Moderate</option>
                    <option>Fast-Paced</option>
                  </select>
                </div>
              </div>
              <button
                type="submit"
                disabled={loading}
                aria-label={loading ? "Initializing engine" : "Generate initial itinerary"}
                className="w-full bg-indigo-600 hover:bg-indigo-500 disabled:bg-zinc-800 py-3 rounded-xl font-bold transition shadow-lg shadow-indigo-500/20 active:scale-[0.98] outline-none focus-visible:ring-2 focus-visible:ring-indigo-300"
              >
                {loading ? <RefreshCw className="w-5 h-5 animate-spin mx-auto" /> : 'INITIALIZE ENGINE'}
              </button>
            </form>
          </section>

          <section className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-6" aria-labelledby="sim-title">
            <h2 id="sim-title" className="text-xs font-bold text-zinc-500 uppercase tracking-[0.2em] mb-4 flex items-center gap-2">
              <Terminal className="w-4 h-4" /> Simulation Center
            </h2>
            <div className="space-y-3">
              <button
                onClick={() => handleSimulatedPivot('RAIN')}
                aria-pressed={isRainMode}
                aria-label="Toggle heavy rain simulation"
                className={`w-full flex items-center justify-between p-4 rounded-xl border transition-all ${isRainMode ? 'bg-indigo-500/10 border-indigo-500 text-indigo-400' : 'bg-zinc-950 border-zinc-800'} outline-none focus-visible:ring-2 focus-visible:ring-indigo-500`}
              >
                <div className="flex items-center gap-3">
                  <CloudRain className="w-5 h-5" />
                  <span className="text-sm">Trigger Heavy Rain</span>
                </div>
                <div className={`w-2 h-2 rounded-full ${isRainMode ? 'bg-indigo-500 animate-pulse' : 'bg-zinc-700'}`} />
              </button>

              <button
                onClick={() => handleSimulatedPivot('TRAFFIC')}
                aria-pressed={isHeavyTraffic}
                aria-label="Toggle traffic surge simulation"
                className={`w-full flex items-center justify-between p-4 rounded-xl border transition-all ${isHeavyTraffic ? 'bg-amber-500/10 border-amber-500 text-amber-400' : 'bg-zinc-950 border-zinc-800'} outline-none focus-visible:ring-2 focus-visible:ring-amber-500`}
              >
                <div className="flex items-center gap-3">
                  <Car className="w-5 h-5" />
                  <span className="text-sm">Traffic Surge (+30m)</span>
                </div>
                <div className={`w-2 h-2 rounded-full ${isHeavyTraffic ? 'bg-amber-500 animate-pulse' : 'bg-zinc-700'}`} />
              </button>
            </div>
          </section>

          <section className="bg-zinc-900/50 border border-zinc-800 rounded-2xl p-6 h-[250px] flex flex-col" aria-labelledby="log-title">
            <h2 id="log-title" className="text-xs font-bold text-zinc-500 uppercase tracking-[0.2em] mb-4">Reasoning Engine</h2>
            <div 
              className="flex-1 overflow-y-auto space-y-3 font-mono text-[11px] text-zinc-500 scrollbar-hide"
              aria-live="polite"
              role="log"
            >
              <AnimatePresence initial={false}>
                {reasoningLog.map((log, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -5 }}
                    animate={{ opacity: 1, x: 0 }}
                    className="flex gap-2 leading-relaxed"
                  >
                    <span className="text-indigo-500 shrink-0" aria-hidden="true">❯</span>
                    <span>{log}</span>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </section>
        </aside>

        <article className="lg:col-span-8">
          <header className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold tracking-tight">Dynamic Itinerary</h1>
              <p className="text-zinc-500 text-sm mt-1">Real-time route optimization via Google Routes API</p>
            </div>
            {isUpdating && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex items-center gap-2 text-indigo-400 text-xs font-bold px-3 py-1 bg-indigo-500/10 rounded-full border border-indigo-500/20"
                role="status"
              >
                <RefreshCw className="w-3 h-3 animate-spin" />
                PIVOTING LOGIC...
              </motion.div>
            )}
          </header>

          <section className="space-y-4">
            {loading ? (
              <ItinerarySkeleton />
            ) : itinerary.length > 0 ? (
              <div className="relative border-l-2 border-zinc-800 ml-3 pl-8 space-y-8" role="list">
                {itinerary.map((activity) => (
                  <motion.div
                    layout
                    key={activity.id}
                    className="relative"
                    role="listitem"
                  >
                    <div className="absolute -left-[41px] top-1 w-4 h-4 bg-zinc-950 border-2 border-indigo-500 rounded-full z-10" aria-hidden="true" />
                    <div className={`group bg-zinc-900/40 border transition-all duration-500 ${activity.isIndoor && isRainMode ? 'border-indigo-500 shadow-[0_0_20px_rgba(99,102,241,0.1)]' : 'border-zinc-800'} rounded-2xl p-6 hover:bg-zinc-800/50`}>
                      <div className="flex items-start justify-between">
                        <div className="space-y-2">
                          <div className="flex items-center gap-3">
                            <span className="text-xs font-mono text-indigo-400 flex items-center gap-1">
                              <Clock className="w-3 h-3" /> {activity.time}
                            </span>
                            {activity.rating && (
                              <div className="flex items-center gap-1 text-amber-500 text-[10px] font-bold">
                                <span>★</span>
                                <span>{activity.rating}</span>
                              </div>
                            )}
                            {activity.isIndoor && isRainMode && (
                              <span className="text-[9px] font-bold bg-indigo-500 text-white px-2 py-0.5 rounded-sm uppercase tracking-wider">Indoor Pivot Active</span>
                            )}
                          </div>
                          <h3 className="text-xl font-bold">{activity.title}</h3>
                          <p className="text-sm text-zinc-400 leading-relaxed">{activity.description}</p>
                          
                          {activity.googleMapsUrl && (
                            <a 
                              href={activity.googleMapsUrl} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="inline-flex items-center gap-1.5 mt-3 text-[10px] font-bold text-indigo-400 hover:text-indigo-300 transition uppercase tracking-wider"
                            >
                              <MapPin className="w-3 h-3" /> View on Google Maps
                            </a>
                          )}
                          
                          {activity.topReview && (
                            <div className="mt-3 p-3 bg-zinc-950/50 rounded-xl border border-zinc-800/50 italic text-[11px] text-zinc-500 leading-relaxed">
                              "{activity.topReview.substring(0, 120)}..."
                              <div className="mt-1 font-bold text-zinc-600">— Google Local Guide</div>
                            </div>
                          )}
                        </div>
                        <button 
                          aria-label={`View details for ${activity.title}`}
                          className="p-2 bg-zinc-950 rounded-lg group-hover:bg-indigo-600 transition-colors focus-visible:ring-2 focus-visible:ring-indigo-400 outline-none"
                        >
                          <ChevronRight className="w-5 h-5 text-zinc-700 group-hover:text-white" />
                        </button>
                      </div>
                    </div>
                  </motion.div>
                ))}
              </div>
            ) : (
              <div className="h-[400px] border-2 border-dashed border-zinc-800 rounded-3xl flex flex-col items-center justify-center text-zinc-600 gap-4 bg-zinc-950/50">
                <AlertCircle className="w-10 h-10 opacity-20" aria-hidden="true" />
                <p className="text-sm font-medium">No active itinerary. Please configure your trip.</p>
              </div>
            )}
          </section>
        </article>
      </main>
    </div>
  );
}